# Generated by Django 5.1.6 on 2025-02-14 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Darmatologist', 'Darmatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Orthopedic', 'Orthopedic'), ('General Practitioner', 'General Practitioner')], max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('distance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('appointment_date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('symptoms', models.TextField()),
                ('session_type', models.CharField(choices=[('video', 'video call'), ('audio', 'audio call')], default='video', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
            ],
        ),
    ]
