# Generated by Django 5.1.6 on 2025-02-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/logo.png', null=True, upload_to='profile_pics/'),
        ),
    ]
