# Generated by Django 5.1.5 on 2025-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicservices_clinic_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/logo.png', null=True, upload_to='clinics_images'),
        ),
    ]
